<?php

/**
 * Implementation of hook_menu().
 */
function contact_save_menu() {
  $items['admin/reports/contact/submissions'] = array(
    'title' => 'Submissions',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('contact_save_submissions'),
    'access arguments' => array('administer site-wide contact form'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
    'file' => 'contact_save.admin.inc',
  );

  return $items;
}

/**
 * Implementation of hook_mail_alter().
 */
function contact_save_mail_alter(&$message) {
  if ($message['id'] == 'contact_page_mail') {
    $record = array(
      'cid' => isset($message['params']['category']['cid']) ? $message['params']['category']['cid'] : 1,
      'uid' => isset($message['params']['sender']) ? $message['params']['sender']->uid : 0,
      'name' => $message['params']['name'],
      'sender' => $message['params']['mail'],
      'body' => implode('\n', $message['body']),
      'created' => REQUEST_TIME,
    );

    drupal_write_record('contact_save', $record);
  }
}


function contact_save_get_submissions() {
  $query = db_select('contact_save', 'cs');
  $query->fields('cs');
  $query->join('contact', 'c', 'cs.cid = c.cid');
  $query->fields('c', array('category'));
  $query->join('users', 'u', 'cs.uid = u.uid');
  $query->fields('u', array('name'));

  $results = $query->execute()->fetchAllAssoc('id');

  return $results;
}