<?php

require_once 'includes/contact_save.views.inc';

/**
 * Implementation of hook_menu().
 */
function contact_save_menu() {
  $items['admin/reports/contact/settings'] = array(
    'title' => 'Contact save settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('contact_save_settings'),
    'access arguments' => array('administer contact forms'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
    'file' => 'includes/contact_save.admin.inc',
  );

  $items['admin/reports/contact/message/%/delete'] = array(
    'title' => 'Contact save settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('contact_save_message_delete_form', 4),
    'access arguments' => array('administer contact forms'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/contact_save.admin.inc',
  );

  return $items;
}

/**
 * Implementation of hook_mail_alter().
 */
function contact_save_mail_alter(&$message) {
  if ($message['id'] == 'contact_page_mail') {
    $record = array(
      'cid' => isset($message['params']['category']['cid']) ? $message['params']['category']['cid'] : 1,
      'uid' => isset($message['params']['sender']) ? $message['params']['sender']->uid : 0,
      'name' => $message['params']['name'],
      'mail' => $message['params']['mail'],
      'subject' => $message['params']['subject'],
      'message' => implode('\n', $message['body']),
      'created' => REQUEST_TIME,
    );

    drupal_write_record('contact_save', $record);
  }
}

/**
 * Implements hook_views_api().
 */
function contact_save_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'contact_save') . '/includes',
  );
}

function contact_save_get_submissions() {
  $query = db_select('contact_save', 'cs');
  $query->fields('cs');
  $query->join('contact', 'c', 'cs.cid = c.cid');
  $query->fields('c', array('category'));
  $query->join('users', 'u', 'cs.uid = u.uid');
  $query->fields('u', array('name'));

  $results = $query->execute()->fetchAllAssoc('id');

  return $results;
}
